Assignment: Introduction to Linear Algebra and NumPy
Objective:
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.

Working with NumPy
NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

Task 1:

Import the numpy library and check its version.

In [1]:
import numpy as np
np.__version__

'2.5.2'

Creating a NumPy Array:
NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

Task 2:

Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].
Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
Generate an array of 10 evenly spaced values between 0 and 5.

In [4]:
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [6]:
import random
array2=np.random.randint(1,9,size=(3,3))
array2

array([[7, 3, 8],
       [7, 3, 6],
       [4, 3, 5]], dtype=int32)

In [63]:
#Generate an array of 10 evenly spaced values between 0 and 5.
A=np.linspace(0, 5, 10)
A

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


Indexing and Slicing Arrays:
Indexing and slicing allow you to access and modify specific elements of an array.

Task 3:

Access the element in the second row, third column of the 2D array you created above.
Slice the first two rows and the first two columns from the same array.
Modify the value in the last row and first column to 100.

In [5]:
import numpy as np 
import random
array2=np.random.randint(1,9,size=(3,3))
array2

array([[4, 4, 6],
       [3, 1, 1],
       [6, 1, 6]], dtype=int32)

In [6]:
#Access the element in the second row, third column of the 2D array you created above.
array2[1,2]

np.int32(1)

In [7]:
#Slice the first two rows and the first two columns from the same array.
array2[0:2,0:2]

array([[4, 4],
       [3, 1]], dtype=int32)

In [8]:
#Modify the value in the last row and first column to 100.
array2[2,0]=100
array2

array([[  4,   4,   6],
       [  3,   1,   1],
       [100,   1,   6]], dtype=int32)

Properties and Methods of NumPy Arrays
NumPy arrays have several useful properties and methods.

Task 4:

Find the shape, size, and data type of the 2D array.
Change the 1D array into a 2D array of shape (5,1).
Flatten a multi-dimensional array back into a 1D array.

In [9]:
array2.shape

(3, 3)

In [10]:
array2.size

9

In [14]:

array2.dtype

dtype('int32')

In [12]:
array2.data

In [20]:
#Change the 1D array into a 2D array of shape (5,1).
array1=[1,2,3,4,5]
arrayreshape=np.reshape(array1,shape=(5,1))
arrayreshape.shape


(5, 1)

In [19]:
arrayreshape.shape

(5, 1)

In [22]:
#Flatten a multi-dimensional array back into a 1D array.
array3=np.random.randint(1,9,size=(3,3))
array3

array([[5, 1, 7],
       [4, 1, 6],
       [4, 5, 6]], dtype=int32)

In [23]:
flat=array3.flatten()

In [24]:
flat

array([5, 1, 7, 4, 1, 6, 4, 5, 6], dtype=int32)

Operations on NumPy Arrays
Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

Task 5:

Add 5 to every element in the 1D array.
Multiply the 2D array by 3.
Perform matrix multiplication between the following two arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [51]:
import numpy as np

arr1 = np.array([[1, 2, 3],[1,2,3]])
arr2 = np.array([[4, 5, 6],[4,5,6]])


In [50]:
arr3=np.add(arr1,arr2)
arr3

array([[5, 7, 9],
       [5, 7, 9]])

In [52]:
arr3=np.subtract(arr1,arr2)
arr3

array([[-3, -3, -3],
       [-3, -3, -3]])

In [53]:
arr3=np.multiply(arr1,arr2)
arr3

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [56]:
arr1=np.random.randint(1,9,size=(3,3))
arr2=np.random.randint(1,9,size=(3,3))
arr3=np.matmul(arr1,arr2)
arr3

array([[ 19,  30,  17],
       [ 71, 123,  66],
       [ 19,  53,  32]], dtype=int32)

In [57]:
arr1=np.random.randint(1,9,size=(3,3))
arr2=np.random.randint(1,9,size=(3,3))
arr3=arr1@arr2
arr3

array([[41, 26, 61],
       [38, 24, 56],
       [56, 34, 75]], dtype=int32)

In [54]:
arr3=np.divide(arr1,arr2)
arr3

array([[0.25, 0.4 , 0.5 ],
       [0.25, 0.4 , 0.5 ]])

In [61]:
#Add 5 to every element in the 1D array.
A=np.array([1,2,3,4,5])
B=A+5
B

array([ 6,  7,  8,  9, 10])

In [62]:
#Multiply the 2D array by 3.
A = np.array([[1, 2], [3, 4]])
B=A*3
B

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
#Perform matrix multiplication between the following two arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C=A@B
C


array([[19, 22],
       [43, 50]])

In [ ]:
#Perform matrix multiplication between the following two arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C=np.matmul(A,B)
C

array([[19, 22],
       [43, 50]])

Understanding Broadcasting
Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

Task 6:

Create a 3x3 matrix of ones and a 1D array of length 3.
Add the 1D array to each row of the matrix using broadcasting.

In [41]:
arr1=np.ones((3,3), int)

arr2=np.random.randint(1,3,size=(1,3))


In [42]:
arr1


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
arr2

array([[2, 2, 1]], dtype=int32)

In [44]:
array=arr1+arr2
array

array([[3, 3, 2],
       [3, 3, 2],
       [3, 3, 2]])