solve:
4x+2y=8
5x+3y=9

4x=8-2y
x=(8-2y)/4
x=(4-y)/2----i

using in eq ii
5x+3y=9 
using value of x
5((4-y)/2)+3y=9
(20-5y)/2+3y=9
20-5y=(9-3y)*2
20-5y=18-6y
20-18=-y
2=-y
y=-2

x=(4--2)/2
x=3


In [2]:
import numpy as np


In [2]:
np.__version__

'2.5.2'

Creating Numpy Array

In [8]:
list1=[1,2,3,4,5,6,7]
arra1=np.array(list1)

In [9]:
arra1

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
arra1.shape

(7,)

In [ ]:
arra1.ndim#check dimension of an array

1

In [3]:
list2=[
    [1,2,3],
    [4,5,6,],
    [7,8,9]
]
array1=np.array(list2)

In [4]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array1.shape

(3, 3)

In [6]:
array1.ndim

2

In [7]:

list3=[[[1,2,3],[4,5,6],[7,8,9]]
       ,[[1,2,3],[4,5,6],[7,8,9]]]
array2=np.array(list3)

In [8]:
array2.shape

(2, 3, 3)

In [9]:
array2.ndim

3

In [20]:
np.zeros(shape=(3,3,2), dtype=int)                                                                                         

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [21]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.full(shape=(2,3), fill_value=6)

array([[6, 6, 6],
       [6, 6, 6]])

In [24]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [26]:
np.linspace(1,100,num=10, dtype=int)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [27]:
np.linspace((0,2),(30,60), num=13
            )

array([[ 0.        ,  2.        ],
       [ 2.5       ,  6.83333333],
       [ 5.        , 11.66666667],
       [ 7.5       , 16.5       ],
       [10.        , 21.33333333],
       [12.5       , 26.16666667],
       [15.        , 31.        ],
       [17.5       , 35.83333333],
       [20.        , 40.66666667],
       [22.5       , 45.5       ],
       [25.        , 50.33333333],
       [27.5       , 55.16666667],
       [30.        , 60.        ]])

In [28]:
np.linspace((0,2,2),(30,60,90), num=13
            )

array([[ 0.        ,  2.        ,  2.        ],
       [ 2.5       ,  6.83333333,  9.33333333],
       [ 5.        , 11.66666667, 16.66666667],
       [ 7.5       , 16.5       , 24.        ],
       [10.        , 21.33333333, 31.33333333],
       [12.5       , 26.16666667, 38.66666667],
       [15.        , 31.        , 46.        ],
       [17.5       , 35.83333333, 53.33333333],
       [20.        , 40.66666667, 60.66666667],
       [22.5       , 45.5       , 68.        ],
       [25.        , 50.33333333, 75.33333333],
       [27.5       , 55.16666667, 82.66666667],
       [30.        , 60.        , 90.        ]])

In [34]:
np.linspace((0,2,2),(30,60,90), num=3, axis=1
            )

array([[ 0., 15., 30.],
       [ 2., 31., 60.],
       [ 2., 46., 90.]])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.random.randint(0,50,size=(3,2,4))

array([[[33,  1, 38,  1],
        [24,  3, 30, 19]],

       [[ 9,  6, 42, 33],
        [27, 47, 18,  5]],

       [[19, 37, 21, 44],
        [25,  7, 20, 35]]], dtype=int32)