In [1]:
import numpy as np
import random 

In [2]:
a=np.random.randint(10,30,size=(5,2,3))

In [3]:
a.shape

(5, 2, 3)

In [4]:
a.ndim

3

In [5]:
a.dtype

dtype('int32')

In [6]:
a.T

array([[[28, 20, 25, 28, 27],
        [29, 24, 11, 12, 23]],

       [[28, 15, 25, 21, 25],
        [18, 23, 10, 25, 28]],

       [[23, 13, 27, 23, 20],
        [10, 16, 15, 22, 15]]], dtype=int32)

In [7]:
a.size

30

In [8]:
a=np.random.randint(10,50,size=(5,4),dtype="int16")
a

array([[18, 15, 36, 22],
       [19, 47, 44, 39],
       [30, 16, 31, 27],
       [32, 19, 28, 10],
       [39, 35, 16, 40]], dtype=int16)

In [9]:
a.reshape(10,2)

array([[18, 15],
       [36, 22],
       [19, 47],
       [44, 39],
       [30, 16],
       [31, 27],
       [32, 19],
       [28, 10],
       [39, 35],
       [16, 40]], dtype=int16)

In [10]:
b=a.reshape(5,2,2)
b

array([[[18, 15],
        [36, 22]],

       [[19, 47],
        [44, 39]],

       [[30, 16],
        [31, 27]],

       [[32, 19],
        [28, 10]],

       [[39, 35],
        [16, 40]]], dtype=int16)

In [ ]:
a.reshape(4,-1)

array([[18, 15, 36, 22, 19],
       [47, 44, 39, 30, 16],
       [31, 27, 32, 19, 28],
       [10, 39, 35, 16, 40]], dtype=int16)

In [ ]:
a.flatten()#a.ravel()---truns to linear shape like a list

array([18, 15, 36, 22, 19, 47, 44, 39, 30, 16, 31, 27, 32, 19, 28, 10, 39,
       35, 16, 40], dtype=int16)

In [15]:
a

array([[18, 15, 36, 22],
       [19, 47, 44, 39],
       [30, 16, 31, 27],
       [32, 19, 28, 10],
       [39, 35, 16, 40]], dtype=int16)

In [16]:
a.sum()

np.int64(563)

In [ ]:
a.sum(axis=0) #column wise when axis=0 and row-wise operation when axis=1

array([138, 132, 155, 138])

In [18]:
a.sum(axis=1)

array([ 91, 149, 104,  89, 130])

In [23]:
a.trace()

np.int64(106)

In [24]:
a

array([[18, 15, 36, 22],
       [19, 47, 44, 39],
       [30, 16, 31, 27],
       [32, 19, 28, 10],
       [39, 35, 16, 40]], dtype=int16)

In [20]:
a.cumsum(axis=1)

array([[ 18,  33,  69,  91],
       [ 19,  66, 110, 149],
       [ 30,  46,  77, 104],
       [ 32,  51,  79,  89],
       [ 39,  74,  90, 130]])

In [21]:
a.prod()

np.int64(-5454030061667614720)

In [25]:
a.cumprod(axis=1)

array([[     18,     270,    9720,  213840],
       [     19,     893,   39292, 1532388],
       [     30,     480,   14880,  401760],
       [     32,     608,   17024,  170240],
       [     39,    1365,   21840,  873600]])

In [ ]:
a.argmax()# points out the index

np.int64(5)

In [27]:
a.argmin()

np.int64(15)

In [28]:
a.clip(min=20, max=40)

array([[20, 20, 36, 22],
       [20, 40, 40, 39],
       [30, 20, 31, 27],
       [32, 20, 28, 20],
       [39, 35, 20, 40]], dtype=int16)

In [30]:
#Concat or Joining
arr1=np.random.randint(1,100, size=(3,3) )
arr2=np.random.randint(1,100, size=(3,3) )


In [31]:
arr1, arr2

(array([[ 3, 26, 71],
        [ 4, 86, 33],
        [13, 83, 82]], dtype=int32),
 array([[93, 27, 95],
        [43,  6, 70],
        [51, 93, 75]], dtype=int32))

In [34]:
np.concat([arr1,arr2])

array([[ 3, 26, 71],
       [ 4, 86, 33],
       [13, 83, 82],
       [93, 27, 95],
       [43,  6, 70],
       [51, 93, 75]], dtype=int32)

In [35]:
np.concatenate([arr1,arr2])

array([[ 3, 26, 71],
       [ 4, 86, 33],
       [13, 83, 82],
       [93, 27, 95],
       [43,  6, 70],
       [51, 93, 75]], dtype=int32)

In [ ]:
np.concatenate([arr1,arr2],axis=1)# can use hstack

array([[ 3, 26, 71, 93, 27, 95],
       [ 4, 86, 33, 43,  6, 70],
       [13, 83, 82, 51, 93, 75]], dtype=int32)

In [39]:
np.concatenate([arr1,arr2],axis=0) # can use vstack

array([[ 3, 26, 71],
       [ 4, 86, 33],
       [13, 83, 82],
       [93, 27, 95],
       [43,  6, 70],
       [51, 93, 75]], dtype=int32)

In [40]:
np.vstack([arr1,arr2])

array([[ 3, 26, 71],
       [ 4, 86, 33],
       [13, 83, 82],
       [93, 27, 95],
       [43,  6, 70],
       [51, 93, 75]], dtype=int32)

In [41]:
np.hstack([arr1,arr2])

array([[ 3, 26, 71, 93, 27, 95],
       [ 4, 86, 33, 43,  6, 70],
       [13, 83, 82, 51, 93, 75]], dtype=int32)