In [2]:
import numpy as np

In [6]:
a= np.array([
    [4,5,8],
    [1,2,4]
]
)

b= np.random.randint(1,45, size= (2,3))
c= np.linspace((0,5), (60,100), num=4,dtype=int)

In [7]:
np.add(a,b)

array([[40, 18, 45],
       [12, 30, 20]])

In [8]:
np.pow(a,2)

array([[16, 25, 64],
       [ 1,  4, 16]])

In [9]:
quo,rem=np.divmod(b,a)
rem


array([[0, 3, 5],
       [0, 0, 0]])

Trigonometric Operation

In [12]:
np.sin(a)

array([[-0.7568025 , -0.95892427,  0.98935825],
       [ 0.84147098,  0.90929743, -0.7568025 ]])

In [15]:
cot=np.reciprocal(np.tan(b))
cot

array([[ 0.12902442,  2.15972864, -1.18938414],
       [-0.00442574, -3.55328645,  3.3263232 ]])

In [16]:
np.around(cot,2)

array([[ 0.13,  2.16, -1.19],
       [-0.  , -3.55,  3.33]])

In [17]:
np.floor(cot)

array([[ 0.,  2., -2.],
       [-1., -4.,  3.]])

In [18]:
np.ceil(cot)

array([[ 1.,  3., -1.],
       [-0., -3.,  4.]])

In [19]:
np.positive(a)

array([[4, 5, 8],
       [1, 2, 4]])

Matrix Operation

In [ ]:
#Matrix Multiplication
a.T# for Transpose

array([[4, 1],
       [5, 2],
       [8, 4]])

In [21]:
c=a.transpose()

In [22]:
c

array([[4, 1],
       [5, 2],
       [8, 4]])

In [23]:
#Matrix Multiplication
#np.dot(a,c)

In [27]:
res=a.dot(c)

In [29]:
#Trace (diagonal sum)
d_sum=np.trace(res)
d_sum

np.int64(126)

In [30]:
#Rank
np.linalg.matrix_rank(a)

np.int64(2)

In [32]:
#Determinant
np.linalg.det(b)# only square matrix can have determinants

LinAlgError: Last 2 dimensions of the array must be square

In [38]:
#determinant
import random
d=np.random.randint(1,5, size=(3,3))
det_d=np.linalg.det(d)
det_d

np.float64(-30.000000000000014)

In [39]:
#Inverse
inv_d=np.linalg.inv(d)
inv_d

array([[-0.5       ,  0.        ,  0.5       ],
       [ 0.3       ,  0.26666667, -0.36666667],
       [ 0.3       , -0.06666667, -0.03333333]])

In [ ]:
np.dot(d,inv_d)

solve: 4x+2y=8,5x+3y=9

In [40]:
A=np.array([[4,2],[5,3]])
B=np.array([8,9])

A_inv=np.linalg.inv(A)

In [41]:
X=np.dot(A_inv,B)
X

array([ 3., -2.])

In [46]:
#Array Broadcasting
A
B
A+B

array([[12, 11],
       [13, 12]])