In [1]:
import numpy as np

In [2]:
array1=np.array([[15,16,17],[25,26,27],[35,36,37],[45,46,47]])

In [3]:
array1[1:3,:1]

array([[25],
       [35]])

In [4]:
arr = [10, 20, 30, 40, 50]
print(arr[1:4])
#[20,30,40]

[20, 30, 40]


In [5]:
arr = [10, 20, 30, 40, 50]
print(arr[:3])
#[10,20,30]

[10, 20, 30]


In [6]:
arr = [10, 20, 30, 40, 50]
print(arr[2:])
#[30,40,50]

[30, 40, 50]


In [7]:
arr = [10, 20, 30, 40, 50]
print(arr[:])
#[10,20,30,40,50]

[10, 20, 30, 40, 50]


In [8]:
arr = [1, 2, 3, 4, 5, 6]
print(arr[0:3])
#[1,2,3]

[1, 2, 3]


In [9]:
arr = [1, 2, 3, 4, 5, 6]
print(arr[3:6])
#[4,5,6]

[4, 5, 6]


In [10]:
arr = [5, 10, 15, 20, 25, 30]
print(arr[1:5])
#[10,15,20,25]

[10, 15, 20, 25]


In [11]:
arr = ['a', 'b', 'c', 'd', 'e']
print(arr[2:4])
#['c','d']

['c', 'd']


Negative indexing

In [12]:
arr = [10, 20, 30, 40, 50]
print(arr[-3:])
#[30,40,50]

[30, 40, 50]


In [13]:
arr = [10, 20, 30, 40, 50]
print(arr[:-2])
#[10,20,30]

[10, 20, 30]


In [14]:
arr = [10, 20, 30, 40, 50]
print(arr[-4:-1])
#[20,30,40]

[20, 30, 40]


In [15]:
arr = [1, 2, 3, 4, 5, 6, 7]
print(arr[-5:-2])
#[3,4,5]

[3, 4, 5]


In [16]:
arr = ['a', 'b', 'c', 'd', 'e', 'f']
print(arr[-1:])
#['f]

['f']


In [17]:
arr = ['a', 'b', 'c', 'd', 'e', 'f']
print(arr[-4:])
#['c','d','e','f']

['c', 'd', 'e', 'f']


In [20]:
arr = [10, 20, 30, 40, 50, 60, 70]
print(arr[-5:-2])

[30, 40, 50]


In [21]:
arr = [10, 20, 30, 40, 50, 60, 70]
arr[-3:]

[50, 60, 70]

Level 3 — Step

Now introduce the third slicing parameter.

In [22]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]
print(arr[::2])
#[1,3,5,7]

[1, 3, 5, 7]


In [23]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]
print(arr[1::2])
#[2,4,6,8]

[2, 4, 6, 8]


In [24]:
arr = [10, 20, 30, 40, 50, 60, 70, 80]
print(arr[1:7:2])
#[20,40,60]

[20, 40, 60]


In [25]:
arr = [10, 20, 30, 40, 50, 60, 70, 80]
print(arr[::3])
#[10,40,70]

[10, 40, 70]


In [26]:
arr = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
print(arr[1:6:2])
#['b','d','f']

['b', 'd', 'f']


In [27]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#What slice would you use to get every second element?
arr[::2]

[1, 3, 5, 7, 9]

In [28]:
#What slice would you use to get:
#[2, 4, 6, 8, 10]
arr[1::2]

[2, 4, 6, 8, 10]

In [29]:
# 🔴 Level 4 — Reverse Slicing

# This is where slicing gets more interesting.

In [ ]:
arr = [1, 2, 3, 4, 5]
print(arr[::-1])
#[5,4,3,2,1]

[5, 4, 3, 2, 1]


In [31]:
arr = [10, 20, 30, 40, 50, 60]
print(arr[5:1:-1])
#[60,50,40,30]

[60, 50, 40, 30]


In [32]:
arr = ['a', 'b', 'c', 'd', 'e', 'f']
print(arr[::-2])
#['f','d','b']

['f', 'd', 'b']


In [34]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]
print(arr[6:1:-2])
#[7,5,3]

[7, 5, 3]


In [35]:
arr = [10, 20, 30, 40, 50]
print(arr[-1:-4:-1])
#[50,40,30]

[50, 40, 30]


In [36]:
arr = [1, 2, 3, 4, 5, 6]
#rite a slice that reverses this array:
arr[::-1]

[6, 5, 4, 3, 2, 1]

In [37]:
#[6, 4, 2]
arr[::-2]

[6, 4, 2]

Level 5 — Tricky Slicing

Don't run these. Carefully reason through the indexes.

In [38]:
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(arr[2:8:2])
#[2,4,6]

[2, 4, 6]


In [39]:
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(arr[8:2:-2])
#[8,6,4]

[8, 6, 4]


In [40]:
arr = [10, 20, 30, 40, 50, 60, 70]
print(arr[-2:-6:-1])
#[60,50,40,30]

[60, 50, 40, 30]


In [42]:
arr = [1, 2, 3, 4, 5, 6, 7]
print(arr[5:0:-2])
#[6,4,2]

[6, 4, 2]


In [ ]:
arr = [1, 2, 3, 4, 5]
print(arr[4:0])
#[] as if the index must move from high to low negative step is required

[]


In [ ]:
arr = [1, 2, 3, 4, 5]
print(arr[0:4:-1])
#[] as  it moves in opposite direction python cant make slice

[]


In [45]:
arr = [10, 20, 30, 40, 50, 60]
print(arr[-1:-7:-2])
#[60,40,20]

[60, 40, 20]


In [47]:
arr = list(range(20))
print(arr[15:3:-3])

#[15,12,9,6]

[15, 12, 9, 6]


In [48]:
arr = list(range(15))
print(arr[12:2:-2])
#[12,10,8,6,4]

[12, 10, 8, 6, 4]


In [49]:
arr = list(range(10))
print(arr[-2:-9:-3])
#[8,5,2]

[8, 5, 2]


In [55]:
arr = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [56]:
# #[
#     [1, 2, 3, 4],
#     [5, 6, 7, 8]
# ]
arr[:2,0:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
#Get the last two rows.
arr[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
#Get rows 1 and 2.
arr[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
#Get the first two columns from every row.
arr[::,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [ ]:
#Get the last two columns.
arr[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

2D — Rows + Columns Together
arr[rows, columns]

In [64]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
# [
#     [6, 7],
#     [10, 11]
# ]
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [67]:
# [
#     [2, 3, 4],
#     [6, 7, 8]
# ]
arr[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [68]:
# [
#     [9, 10],
#     [13, 14]
# ]
arr[2:,:2]

array([[ 9, 10],
       [13, 14]])

In [70]:
# [
#     [6, 7],
#     [10, 11]
# ]
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [71]:
# [
#     [3, 4],
#     [7, 8],
#     [11, 12],
#     [15, 16]
# ]
arr[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [69]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

3D array
arr[layer, row, column]

In [72]:
import numpy as np

arr = np.arange(1, 25).reshape(2, 3, 4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [74]:
arr[0, :, :]
# #[ 1,  2,  3,  4],
#         [ 5,  6,  7,  8],
#         [ 9, 10, 11, 12]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
arr[1, :, :]
# #[13, 14, 15, 16],
#         [17, 18, 19, 20],
#         [21, 22, 23, 24]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
arr[:, 0, :]
#[ 1,  2,  3,  4],
#[13, 14, 15, 16]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [77]:
import numpy as np

arr = np.arange(1, 65).reshape(4, 4, 4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])

In [83]:
# [
#   [
#     [64, 62],
#     [56, 54]
#   ],
#   [
#     [48, 46],
#     [40, 38]
#   ]
# ]
arr[3:1:-1,-1::-2,-1::-2]

array([[[64, 62],
        [56, 54]],

       [[48, 46],
        [40, 38]]])